### ISSUE TITLE
Error on any request

### ISSUE THREAD

**Issue by lenzls** [gramps-project/gramps-webapi#192]
Hello,

first, I wanted to say, that I'm very excited about the project. I'm thinking more and more about how to involve other people more into my research. A web application (let alone edit functionality), is what I wished for a long time.

Currently, I'm having trouble running the thing though.

I tried to follow the instructions on the wiki on running with docker-compose.

It seems, that the service is starting up correctly, but at any request, I get the following error:

```
gramps_webapi_1  | Traceback (most recent call last):
gramps_webapi_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/sync.py", line 182, in handle_request
gramps_webapi_1  |     resp.write_file(respiter)
gramps_webapi_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/http/wsgi.py", line 385, in write_file
gramps_webapi_1  |     if not self.sendfile(respiter):
gramps_webapi_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/http/wsgi.py", line 375, in sendfile
gramps_webapi_1  |     self.sock.sendfile(respiter.filelike, count=nbytes)
gramps_webapi_1  |   File "/usr/lib/python3.7/socket.py", line 402, in sendfile
gramps_webapi_1  |     return self._sendfile_use_sendfile(file, offset, count)
gramps_webapi_1  |   File "/usr/lib/python3.7/socket.py", line 266, in _sendfile_use_sendfile
gramps_webapi_1  |     self._check_sendfile_params(file, offset, count)
gramps_webapi_1  |   File "/usr/lib/python3.7/socket.py", line 381, in _check_sendfile_params
gramps_webapi_1  |     "count must be a positive integer (got {!r})".format(count))
gramps_webapi_1  | ValueError: count must be a positive integer (got 0)
```

## My setup

`config.cfg`
```
TREE="<mytree>"
SECRET_KEY="0redacted"
USER_DB_URI="sqlite:////app/users/users.sqlite"
MEDIA_BASE_DIR="/app/media"
SEARCH_INDEX_DIR="/app/indexdir"
STATIC_PATH="/app/static"
```

`docker-compose.yaml`
```
version: "3.7"

services:
  gramps_webapi:
    image: dmstraub/gramps-webapi:latest
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - gramps_users:/app/users
      - gramps_index:/app/indexdir
      - gramps_thumb_cache:/app/thumbnail_cache
      -./web-api-config.cfg:/app/config/config.cfg
      - /home/<myname>/.gramps/grampsdb:/root/.gramps/grampsdb
      - /home/<myname>/files:/app/media 

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
```

It looks like in principle things are working. If I change `TREE=`  in the config to a non-existent one, I get a correct error message on startup, for example.

Any ideas what could go wrong here?
